# Generated by Django 4.2.7 on 2023-11-15 05:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Admin ID must be a combination of 3 uppercase characters followed by 3 to 5 numbers.', regex='^([a-z]{0,5}[A-Z]{0,5}\\d{3,5})$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('reg_date', models.DateField(default=datetime.date.today)),
                ('username', models.CharField(default='username', max_length=100)),
                ('is_admin', models.CharField(default='yes', editable=False, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100, unique=True)),
                ('dep_short_name', models.CharField(max_length=5)),
                ('dep_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^([A-Z]{0,5}\\d{0,5})*$')])),
                ('reg_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9]*$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('dep', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('username', models.CharField(default='username', max_length=100)),
                ('is_admin', models.CharField(default='no', editable=False, max_length=3)),
                ('reg_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('leave_type', models.CharField(max_length=100)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('Status', models.CharField(default='pending', max_length=12)),
            ],
            options={
                'permissions': [('can_change_leave_status', 'Can change leave status')],
            },
        ),
        migrations.CreateModel(
            name='leavetypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100, unique=True)),
                ('leave_code', models.CharField(default='AAA000', max_length=10, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^([A-Z]{0,5}\\d{0,5})*$')])),
                ('description', models.TextField(null=True)),
                ('reg_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
